spring:
  security:
    saml2:
      relyingparty:
        registration:
          asgardeo-saml:
            identityprovider:
              entity-id: api.asgardeo.io/t/samplewebapp
              verification:
                credentials:
                  - certificate-location: "classpath:saml-certificate/samplewebapp.cer"
              singlesignon:
                url: https://api.asgardeo.io/t/samplewebapp/samlsso
                sign-request: false